### ISSUE TITLE
20160415优酷电视剧日报导出有问题

### ISSUE THREAD

**Issue by rosicky1985** [rosicky1985/spider#11]
```
org.hibernate.NonUniqueResultException: query did not return a unique result: 2
        at org.hibernate.impl.AbstractQueryImpl.uniqueElement(AbstractQueryImpl.java:868)
        at org.hibernate.impl.AbstractQueryImpl.uniqueResult(AbstractQueryImpl.java:859)
        at com.nbb.spider.dao.impl.PersonDaoImpl.getByName(PersonDaoImpl.java:17)
        at com.nbb.spider.dao.impl.PersonDaoImpl.getByName(PersonDaoImpl.java:1)
        at com.nbb.spider.manager.task.impl.DimensionParser.parseFromStringTokens(DimensionParser.java:22)
        at com.nbb.spider.manager.task.impl.letv.LetvTaskRunner$Runner.parseOneline(LetvTaskRunner.java:83)
        at com.nbb.spider.manager.task.impl.letv.LetvTaskRunner.run(LetvTaskRunner.java:60)
        at com.nbb.spider.manager.webspider.TaskRunnerManager.runOneDs(TaskRunnerManager.java:99)
        at com.nbb.spider.manager.webspider.TaskRunnerManager.runAType(TaskRunnerManager.java:81)
        at com.nbb.spider.manager.webspider.TaskRunnerManager.runDaily(TaskRunnerManager.java:73)
        at com.nbb.spider.manager.webspider.TaskRunnerManager$$FastClassByCGLIB$$b628b8c6.invoke(<generated>)
        at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:191)
        at org.springframework.aop.framework.Cglib2AopProxy$CglibMethodInvocation.invokeJoinpoint(Cglib2AopProxy.java:688)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:110)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:621)
        at com.nbb.spider.manager.webspider.TaskRunnerManager$$EnhancerByCGLIB$$f2d21308.runDaily(<generated>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
        at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:264)
        at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:86)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:529)
```

**Comment by rosicky1985** [comment]
```
mysql> select name from person group by name having count(*) >= 2;
+-----------+
| name      |
+-----------+
| 何蕊孜    |
| 张舸      |
+-----------+
2 rows in set (0.05 sec)

mysql> select * from person where name = '何蕊孜';
+-------+-----------+
| id    | name      |
+-------+-----------+
| 11898 | 何蕊孜    |
| 11899 | 何蕊孜    |
+-------+-----------+
2 rows in set (0.00 sec)

mysql> select * from person where name = '张舸';
+-------+--------+
| id    | name   |
+-------+--------+
| 11896 | 张舸   |
| 11897 | 张舸   |
+-------+--------+
2 rows in set (0.01 sec)
mysql> delete from person where id in (11897,11899);
Query OK, 2 rows affected (0.12 sec)

mysql> select name from person group by name having count(*) >= 2;
Empty set (0.04 sec)


mysql> select * from item_actors where actor_id in (11897,11899);
+---------+---------+----------+
| id      | item_id | actor_id |
+---------+---------+----------+
| 1827064 |  440427 |    11897 |
| 1827521 |  440421 |    11899 |
+---------+---------+----------+
2 rows in set (0.38 sec)

mysql> update item_actors set actor_id = 11896 where actor_id = 11897;
Query OK, 1 row affected (0.57 sec)
Rows matched: 1  Changed: 1  Warnings: 0

mysql> update item_actors set actor_id = 11898 where actor_id = 11899;
Query OK, 1 row affected (0.58 sec)
Rows matched: 1  Changed: 1  Warnings: 0

mysql> select * from item_actors where actor_id in (11897,11899);
Empty set (0.37 sec)
```

**Comment by rosicky1985** [comment]
结案:
1 优酷没改版.
2 数据库有重名的人物存在.
